### PR TITLE
`/covid` commands

### LINKED ISSUE #1: /covid
`/covid` - info covid seluruh dunia dan indonesia
`/covid <nama_negara>`  - info covid di negara tertentu

### PR DESCRIPTION
**Pull request by aldy505**
closes #1 

usage:
* `/covid` - Global covid-19 data summary + Indonesia data summary
* `/covid <country>` - Covid-19 data summary for that specific country.

### CODE REVIEW

**Review by artileda — APPROVED** [review]
LGTM

**Comment by lamualfa** [comment]
Kalau aku sih yes! 

*_Nada iklan shampoo Pantene_

**Comment by lamualfa** [comment]
Hold on, bentar, ada yang mau sy revisi sedikit aja xixixi.

**Comment by lamualfa** [comment]
Thanks

**Pull request merged**
